/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // permite hacer una aplicación CLI en Java
    application
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val javafxVersion = "20"


dependencies {
    // Se configura JUnit para testeo
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    testImplementation(libs.junit.jupiter.engine)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Añade la dependencia de Guava de Google, que tiene funcionalidades para trabajar con colecciones, caching, primitivas, concuerrencias, etc.
    implementation(libs.guava)

    //Dependencias de JavaFX
    listOf("base", "controls", "fxml", "graphics").forEach { module ->
        implementation("org.openjfx:javafx-$module:$javafxVersion") {
            artifact {
                //esta configuración es específicamente para Linux
                classifier = "linux"
            }
        }
    }
}


// Configura los argumentos de la JVM para ejecutar una aplicación JavaFX
tasks.named<JavaExec>("run") {
    val osName = "linux"
    val javafxModules = listOf("javafx.controls", "javafx.fxml")

    jvmArgs = listOf(
        "--module-path", configurations.runtimeClasspath.get().asPath,
        "--add-modules", javafxModules.joinToString(",")
    )
}



// Configura la toolchain para usar Java 21. 
// Toolchain: conjunto de programas o herramientas de software que se utilizan de forma secuencial para crear un producto. Estas herramientas trabajan en conjunto, donde la salida de una se convierte en la entrada de la siguiente, permitiendo automatizar y estandarizar tareas complejas para lograr eficiencia y reducir errores. 

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


//Se configura la clase principal de la aplicación para que incie con AppJavaFX
application {
    // Define the main class for the application.
    mainClass = "org.example.AppJavaFXKt"
}


//Se configura JUnit Platform para testeo con la tarea test.
tasks.named<Test>("test") {
    useJUnitPlatform()
}

tasks.test {
    useJUnitPlatform()
    filter {
        isFailOnNoMatchingTests = false
    }
}






